### ISSUE TITLE
Make durable for restart Pod

### ISSUE THREAD

**Issue by okamototk** [eclipse-tractusx/tutorial-resources#317]
### Description

When postgres and minio will restart by failure or reboot node, all data will be deleted miw, tractusx controller, minio and azurite.
I need to reconstruct MXD every time after reboot laptop. 

### Acceptance Criteria

- Work MXD properly after reboot kind node.
  - PostgreSQL will not lost data.
    - miw  will work properly.
    - keycloak will work properly.
    -  control plane will work properly.
  - Minio will not lost data.

### Additional Information
PostgreSQL and Minio should be deploy as StatefulSet and use PVC for their data directory.

**Comment by hemantxpatel** [comment]
Hi @okamototk, thanks for reporting. We are aware about it and it is intentionally by design.
MXD is mostly for tutorial purposes and shouldn't be consider as production ready. We want to keep it very minimal to have minimum resource requirement as most of the time developers run it on their laptop.
